name: Executar gera_plantao.py diariamente

on:
  schedule:
    - cron: '0 6 * * *'  # Executa diariamente às 3h da manhã (horário de Brasília)
  workflow_dispatch:     # Permite execução manual via interface do GitHub

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar o script
        env:
          CREDENCIAIS_JSON: ${{ secrets.CREDENCIAIS_JSON }}
        run: |
          python gera_plantao.py
